[project]
name = "finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.5",
    "feedparser>=6.0.12",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "pandas-ta>=0.4.71b0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "rich>=14.3.3",
    "schedule>=1.2.2",
    "sqlalchemy>=2.0.0",
    "tenacity>=9.1.4",
    "yfinance>=1.2.0",
]
